<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SDF4110CUB050" ignored="0" name="Default test" tests="1" failures="0" timestamp="28 Aug 2017 10:49:20 GMT" time="0.073" errors="0">
  <testcase name="@BeforeTest setup" time="0.0" classname="com.test.automation.uiAutomation.homePage.TC_001_VerifyLoginWithInvalidCredentials">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.test.automation.uiAutomation.testBase.TestBase.getUrl(TestBase.java:29)
	at com.test.automation.uiAutomation.testBase.TestBase.init(TestBase.java:16)
	at com.test.automation.uiAutomation.homePage.TC_001_VerifyLoginWithInvalidCredentials.setup(TC_001_VerifyLoginWithInvalidCredentials.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:144)
	at org.testng.TestRunner.beforeRun(TestRunner.java:634)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- @BeforeTest setup -->
  <testcase name="@AfterClass endTest" time="0.0" classname="com.test.automation.uiAutomation.homePage.TC_001_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- @AfterClass endTest -->
  <testcase name="verifyLoginWithInvalidCredentials" time="0.002" classname="com.test.automation.uiAutomation.homePage.TC_001_VerifyLoginWithInvalidCredentials">
    <skipped/>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
</testsuite> <!-- Default test -->
